### ISSUE TITLE
Week 5 morning session code review

### ISSUE THREAD

**Issue by michaelamponsah** [gauravgangwarweb/Travellers-Fest-Capstone-One-#2]
**@gauravgangwarweb, good job implementing the required features**

**There are still a few changes to be made. ♻**

-  In the features section, It would be appropriate you left aligned your descriptions according to the design document

**Comment by bill7pearl** [comment]
Kindly remove the white border in the <hr> line
<img width="223" alt="bugweek5" src="https://user-images.githubusercontent.com/77294268/203923419-28e6f4cb-8f1f-44dd-9dad-3be2d9f1c8c6.PNG">

**Comment by gitbygaurav** [comment]
Thank you for the review it was great to implement those changes.
